# -*- coding: utf-8 -*-
"""Performance_metrics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1U84r00O--kt5oXFtzTICxut8g-Geor
"""

import numpy as np
import matplotlib.pyplot as plt

# Function to parse joint_state_data.txt (example implementation)
def parse_joint_state(file_path):
    with open(file_path, 'r') as file:
        data = file.read()
    messages = data.split('---\n')
    cart_positions = []
    pendulum_angles = []
    for msg in messages:
        lines = msg.splitlines()
        position_values = []
        capture = False
        for line in lines:
            stripped_line = line.strip()
            if stripped_line == 'position:':
                capture = True
                continue
            if capture and stripped_line.startswith('-'):
                value = float(stripped_line[1:].strip())
                position_values.append(value)
            elif capture:
                break
        if len(position_values) >= 3:
            cart_positions.append(position_values[1])  # cart_to_base
            pendulum_angles.append(position_values[2])  # pole_joint
    return np.array(cart_positions), np.array(pendulum_angles)

# Function to parse control_force_data.txt (example implementation)
def parse_control_force(file_path):
    with open(file_path, 'r') as file:
        data = file.read()
    forces = [float(line.split(': ')[1]) for line in data.splitlines() if 'data:' in line]
    return np.array(forces)

# Load and parse the data
cart_positions, pendulum_angles = parse_joint_state('joint_state_data.txt')
control_forces = parse_control_force('control_force_data.txt')

# Compute metrics
max_cart_displacement = np.max(np.abs(cart_positions))
max_angle_deviation = np.max(np.abs(np.rad2deg(pendulum_angles)))
max_control_force = np.max(np.abs(control_forces))
avg_control_force = np.mean(np.abs(control_forces))

# Print results (matches your output)
print(f"Max Cart Displacement: {max_cart_displacement:.2f} m")
print(f"Max Angle Deviation: {max_angle_deviation:.2f} deg")
print(f"Max Control Force: {max_control_force:.2f} N")
print(f"Avg Control Force: {avg_control_force:.2f} N")

# Generate time array
time_step = 0.1  # seconds, assumed constant time step
time = np.arange(0, len(cart_positions) * time_step, time_step)

# Optional: Warn if lengths differ
# if len(time) != len(control_forces):
#     print(f"Warning: Number of joint state measurements ({len(time)}) and control force measurements ({len(control_forces)}) differ. Plotting overlapping data.")

# Create visualizations
plt.figure(figsize=(12, 8))

# Plot 1: Cart Position over Time
plt.subplot(3, 1, 1)
plt.plot(time, cart_positions, label='Cart Position', color='blue')
plt.xlabel('Time (s)')
plt.ylabel('Position (m)')
plt.title('Cart Position over Time')
plt.grid(True)
plt.legend()

# Plot 2: Pendulum Angle over Time
plt.subplot(3, 1, 2)
plt.plot(time, np.rad2deg(pendulum_angles), label='Pendulum Angle', color='green')
plt.xlabel('Time (s)')
plt.ylabel('Angle (deg)')
plt.title('Pendulum Angle over Time')
plt.grid(True)
plt.legend()

# Plot 3: Control Force over Time (Fixed)
plt.subplot(3, 1, 3)
min_length = min(len(time), len(control_forces))
plt.plot(time[:min_length], control_forces[:min_length], label='Control Force', color='red')
plt.xlabel('Time (s)')
plt.ylabel('Force (N)')
plt.title('Control Force over Time')
plt.grid(True)
plt.legend()

# Adjust layout and display
plt.tight_layout()
plt.show()