# -*- coding: utf-8 -*-
"""colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-o897qsHcqiRnPIkwOJ3cmyfPtrn88x
"""

import matplotlib.pyplot as plt
import numpy as np

# Load cleaned error data
errors = np.loadtxt("/content/error_data.txt")
plt.figure(figsize=(10,4))
plt.plot(errors, color='blue', linewidth=0.5)
plt.title("Cross-Track Error Analysis\nAverage: {:.3f}, Max: {:.3f}".format(np.mean(errors), np.max(errors)))
plt.xlabel("Time Steps")
plt.ylabel("Error (units)")
plt.grid(True, alpha=0.3)
plt.savefig("error_plot.png", dpi=300)

import numpy as np
import matplotlib.pyplot as plt

# Load raw error data (with signs)
signed_errors = np.loadtxt("/content/error_data (2).txt")

# Calculate absolute errors
absolute_errors = np.abs(signed_errors)

# Metrics calculation
avg_error = np.mean(absolute_errors)
max_error = np.max(absolute_errors)
std_dev = np.std(absolute_errors)

print(f"""
Performance Metrics:
- Average Absolute Error: {avg_error:.3f} units
- Maximum Absolute Error: {max_error:.3f} units
- Error Standard Deviation: {std_dev:.3f} units
""")

# Plotting both signed and absolute errors
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12,8))

# Signed errors plot
ax1.plot(signed_errors, color='#3498db', linewidth=0.8)
ax1.set_title("Signed Cross-Track Error")
ax1.set_ylabel("Error (units)")
ax1.axhline(0, color='#2c3e50', linestyle='--', linewidth=1)
ax1.grid(alpha=0.3)

# Absolute errors plot
ax2.plot(absolute_errors, color='#e74c3c', linewidth=0.8)
ax2.set_title("Absolute Cross-Track Error")
ax2.set_xlabel("Time Steps")
ax2.set_ylabel("Error (units)")
ax2.grid(alpha=0.3)

plt.tight_layout()
plt.savefig("error_analysis_complete.png", dpi=300)